name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Updated Python version to 3.9
    
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip  # Upgrade pip to avoid any version issues
        pip install -r requirements.txt
    
    - name: Run bot
      run: |
        source venv/bin/activate
        python bot.py
